name: 🐞 Report a bug
description: Tell us about a bug or issue you may have identified in the app.
title: "[Bug]: Bug Summary"
labels: ["🐞 bug"]
projects: ["B3n-d1v3/2"]
assignees: 
  - B3n-d1v3
body:
  - type: dropdown
    id: type
    attributes:
      label: What device type are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - Android
  - type: input
    id: device
    attributes:
      label: Your device
      description: 
      placeholder: Pixel 2
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: 
      placeholder: Android 10.x
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      placeholder: v2.0.1
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Provide a description of what you expected to happen.
    validations:
      required: true
