name: 🛠️ Feature request
description: Propose your help to add a new language into the Driving Rules mobile app.
title: "[i18n]: Propose new language"
labels: ["🛠️ feature"]
projects: ["B3n-d1v3/2"]
assignees: 
  - B3n-d1v3
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**
        We kindly ask that you check to see if an issue [already exists](https://github.com/B3n-d1v3/diving_rules_hybrid/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%9B%A0%EF%B8%8F++feature%22) for your feature.

  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: |
        Describe the solution you'd like. A clear and concise description of what you want to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
